export const DESIGN_ITEMS = [
  { identifier: "colors", title: "Colors" },
  { identifier: "buttons", title: "Buttons" },
  { identifier: "icons", title: "Icons" },
  { identifier: "anchors", title: "Anchors" },
  { identifier: "cards", title: "Cards" },
  { identifier: "modals", title: "Modals" },
  { identifier: "carousel", title: "Carousel" },
  { identifier: "alert", title: "Alert" },
  { identifier: "row-column", title: "Row - Column" },
  { identifier: "form", title: "Form" },
  { identifier: "table", title: "Table" },
  { identifier: "test-socket", title: "Test Socket" },
  { identifier: "voice-recorder", title: "Voice Recorder" },
  { identifier: "pagination", title: "Pagination" },
  { identifier: "streaming", title: "Streaming" },
  { identifier: "chat-box", title: "Chat Box" },
  { identifier: "connection-to-socket", title: "Connection to Socket" },
];
