# Generated by Django 5.1.6 on 2025-09-17 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai', '0001_enable_pgvector'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AiCost',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service', models.CharField(choices=[('OPEN_AI_COMPLETION', 'OPEN_AI_COMPLETION'), ('OPEN_AI_STT', 'OPEN_AI_STT'), ('OPEN_AI_EMBEDDING', 'OPEN_AI_EMBEDDING'), ('OPEN_AI_TTS', 'OPEN_AI_TTS'), ('OPEN_AI_IMAGE', 'OPEN_AI_IMAGE'), ('GOOGLE_COMPLETION', 'GOOGLE_COMPLETION'), ('GOOGLE_STT', 'GOOGLE_STT'), ('GOOGLE_EMBEDDING', 'GOOGLE_EMBEDDING'), ('GOOGLE_TTS', 'GOOGLE_TTS'), ('GOOGLE_IMAGE', 'GOOGLE_IMAGE')], max_length=255)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_costs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'AI Costs',
                'ordering': ('id',),
            },
        ),
    ]
