# Generated by Django 5.1.6 on 2025-09-17 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aicost',
            name='service',
            field=models.CharField(choices=[('OPEN_AI_COMPLETION', 'OPEN_AI_COMPLETION'), ('OPEN_AI_STT', 'OPEN_AI_STT'), ('OPEN_AI_EMBEDDING', 'OPEN_AI_EMBEDDING'), ('OPEN_AI_TTS', 'OPEN_AI_TTS'), ('OPEN_AI_IMAGE', 'OPEN_AI_IMAGE'), ('GOOGLE_COMPLETION', 'GOOGLE_COMPLETION'), ('GOOGLE_STT', 'GOOGLE_STT'), ('GOOGLE_EMBEDDING', 'GOOGLE_EMBEDDING'), ('GOOGLE_TTS', 'GOOGLE_TTS'), ('GOOGLE_IMAGE', 'GOOGLE_IMAGE'), ('GOOGLE_OCR', 'GOOGLE_OCR')], max_length=255),
        ),
    ]
