# Generated by Django 5.1.6 on 2025-08-26 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='credit',
            field=models.FloatField(default=0.0),
        ),
    ]
